name: movie_application
description: A movie application.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  #Local Notification
  awesome_notifications: any

  #State Management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  #Cache Management
  cached_network_image: ^3.2.0
  hive_flutter: ^1.1.0

  #Slider
  carousel_slider: ^4.0.0

  #Responsive
  flutter_screenutil: ^5.2.0
  kartal: ^2.1.0

  #Slider Widget
  flutter_slidable: ^1.2.0

  #Show Popup
  fluttertoast: ^8.0.8

  #Fonts
  google_fonts: ^2.3.1

  #Formatter
  intl: ^0.17.0

  #Animation
  lottie: ^1.2.1

  #Bottom Navbar
  persistent_bottom_nav_bar: ^4.0.2

  #Share Movie
  share_plus: ^4.0.3

  #Loading Effect
  shimmer: ^2.0.0

  #Redirection to Url
  url_launcher: ^6.0.20

  #Theme Management
  flex_color_scheme: ^4.2.0

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  #Localization
  flutter_localizations:
    sdk: flutter

  #Api Business
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - lang/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
